config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy]


  # root 'book_images#index'

  resources :users, only: [:show, :index, :edit, :update]

  get 'about' => 'users#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/models/book.rb
class Book < ApplicationRecord
	attachment :image
	belongs_to :user

	 validates :body, presence: true
     validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books

  attachment :profile_image

   validates :name, presence: true
   validates :name, length: { minimum: 2, maximum: 20 }
   

   validates :name, presence: true
   validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  
   def after_sign_in_path_for(resource)
   	   user_path(current_user.id)
   end
   def after_sign_out_path_for(resource)
   	   root_path
   end
protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def show
      @book = Book.find(params[:id])
      @user = current_user
      @user = @book.user
      @bookn = Book.new
  end

  def index
      @book = Book.new
      @books = Book.all
      @user = current_user
      @users = User.all
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user != current_user
        redirect_to books_path

      end

  end

  def top
  end
  def create
      # ストロングパラメーターを使用
      book = Book.new(book_params)
      book.user_id = current_user.id
        # DBへ保存する
      if book.save
        # トップ画面へリダイレクト
      flash[:notice] = "successfully"
      redirect_to book_path(book)
      else
      @book = book
      @books = Book.all
      @user = current_user
      @users = User.all
      render :index
    end
  end
  def update
      book = Book.find(params[:id])
      book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(book.id)
  end

  def destroy
     book =Book.find(params[:id])
     book.destroy
     redirect_to books_path
  end

  private

  def book_params
        params.require(:book).permit(:title, :body, :image)
  end

  def correct_user
    # @user = User.find(params[:id])
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!
  def show
  	  @user = User.find(params[:id])
  	  @books = @user.books
  	  @book = Book.new
  end

  def index
  	@users = User.all
  	@book = Book.new
  	@books = Book.all
  	@user =current_user
 end

 def edit
 end
 def update
 	if @user.update(user_params)
    flash[:notice] = "successfully"

 	   redirect_to user_path(@user.id)
 	else
 		render :edit
    end
 end

 private
 def user_params
 	params.require(:user).permit(:name, :profile_image, :introduction)
 end

 def correct_user
 	@user = User.find(params[:id])
 	redirect_to(user_path(current_user)) unless @user == current_user
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!-- <div class="container"> -->
  <p id="notice"></p>
    <!-- <div class="row"> -->
	  <div class="col-xs-3">
	    <h2>User info</h2>


		<table class="table">
		  <tbody>
		    <tr><%= attachment_image_tag @user, :profile_image, format: 'jpeg',fallback: "no_image.jpg", class: "profile_img" %></tr>
			<tr>
				<th>name</th>
				<th><%= user.name %></th>
			</tr>
			<tr>
			   <th>introduction</th>
			   <th><%= user.introduction %></th>
			</tr>
		  </tbody>
		</table>

       <% if user.id == current_user.id %>

        <%= link_to "", edit_user_path(@user.id), class: "btn btn-default edit_user_#{@user.id} glyphicon glyphicon-wrench" %>

       <% end %>

		<h2> New book</h2>
		<%= form_for(book) do |f| %>

		<h4>Title</h4>
		<%= f.text_field :title, class: "book_title" %>

		<h4>Opinion</h4>
		<%= f.text_area :body, class: "book_body" %>
        
        <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
		<% end %>
	  </div>
<!-- 	</div>
</div>
 -->

app/views/books/edit.html.erb
<body>
	
	<div class="body">
		<h1>Editing Book</h1>
		<%= form_for(@book) do |f| %>
		    <h4>タイトル</h4>
		    <%= f.text_field :title, class: "book_title" %>
		    <h4>本文</h4>
		    <%= f.text_area :body, class: "book_body" %>
		    <%= f.submit 'Update Book' %>
		<% end %>
		<%= link_to "show", book_path(@book), class: "show_#{@book.id}" %>

		|
       <%= link_to "Back", books_path, class: "back" %>

     </div>
    
</body>

app/views/books/index.html.erb
<body>

	<% if @book.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= render 'books/list', book_images: @book_images ,user: current_user, book: @book %>




      			<div class="col-xs-9">
      			<h2> Books</h2>
	      		  <table class="table table-hover table-inverse">
			        <thead>
				    	<tr>
				    		<th></th>
				    		<th> Title</th>
				    		<th> Opinion</th>
				    		<th colspan="3"></th>
				    	</tr>
				    </thead>
				    <% @books.each do |book| %>
				    <tbody>
				    	 <tr>
<!-- 				   #book_user -> book.usrに変更
 -->				    	 	<th><%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", :size =>"50x50" %></th>
				    	    <th><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></th>
				    	    <th><%= book.body %></th>
				    	 </tr>
				    </tbody>
				    <% end %>
			      </table>
			    </div>
		    </div>
		</div>
    </div>
	

</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= render 'books/list', book_images: @book_images,user: @book.user, book: @bookn  %>

			      	<div class="col-xs-9">
			      	   <h2> Book detail</h2>
			      	   <table class="table">
			      	   	<tbody>
			      		  <tr>
			      			<td><%= @book.title %></td>
			      			<td><%= @book.body %></td>
			      		  <% if @book.user.id == current_user.id %>
				      		<td><%=link_to "edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
				      		<td><%= link_to "Destroy", book_path(@book), class: "btn-sm btn-danger destroy_book_#{@book.id}", method: :delete, data: { confirm: '本当に消しますか？' } %></td>
				      	  </tr>
			      		  <% end %>
						</tbody>
			      	   </table>
			      	</div>
			</div>
		</div>
	</div>

app/views/books/top.html.erb
<div class="container">


       <p id="notice"></p>

  <div class="row">
     <div class="top-message col-md-offset-3 col-md-6">
       <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
             <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
             <p>you can share and exchange  your opinions , inpressions , and emotions</p>
             <p> about varioius books!</p>

       <div class="btn-wrapper">
         <div class="row">
            <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
         </div>
           <div class="row">
             <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
           </div>
       </div>

     </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar  navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <span> Bookers</span>
          </nav>
          <nav>
             <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="">
                <%= link_to 'Home', user_path(current_user), class: "home glyphicon glyphicon-home" %>
              </li>
              <li class="">
                <%= link_to 'User', users_path, class: "users glyphicon glyphicon-user" %>
              </li>
              <li class="">

                <%= link_to 'Books', books_path(@book), class: "books glyphicon glyphicon-book" %>
              </li>
              <li class="">
                <%= link_to 'logout', destroy_user_session_path,
                method: :delete, class: "logout glyphicon glyphicon-log-out" %>

              </li>
            <% else %>
              <li class="">
                <%= link_to 'Home', root_path(@book), class: "home glyphicon glyphicon-home" %>
              </li>
              <li class="">
                <%= link_to 'About', about_path, class: "about glyphicon glyphicon-link" %>
              </li>
              <li class="">
                <%= link_to 'sign up', new_user_registration_path,class: "sign_up glyphicon glyphicon-edit" %>
              </li>
              <li>
                <%= link_to 'login', new_user_session_path, class: "sign_in glyphicon glyphicon-log-in" %>
            <% end %>

             </ul>
          </nav>
         </div>
    </header>
　　　<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

    <%= yield %>
    <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>


  </body>
</html>

app/views/users/about.erb
<body>
	<div class="body">
    	<div class="container">
        <p id="notice">signed out successfully.</p>
    		<div class="low">
    			<h1>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!!</h1>
    		</div>
        </div>
    </div>
</body>

app/views/users/about.html.erb
<body>
	<div class="body">
    	<div class="container">
        <p id="notice">signed out successfully.</p>
    		<div class="low">
    			<h1>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!!</h1>
    		</div>
        </div>
    </div>
</body>

app/views/users/edit.erb
<div class="error">
<% if @user.errors.any? %>
      <h3> <%= @user.errors.count %> error prohibited this obj from being saved:</h3>
       <% @user.errors.full_messages.each do |message| %>
           <%= message %>
       <% end %>
   <% end %>
  </div>

<div class= "body">
  <div class= "container">
    <h2> User info</h2>
    <div class="low">
	    <%= form_for(@user) do |f| %>
	    <div class="field">
		    <%= f.label :name %>
		      <%= f.text_field :name, autofocus: true, class: "name" %>
	    </div>
	      <div class="field">
	    <%= f.label :image %>
	          <%= f.attachment_field :profile_image, class: "user_image" %>
	      </div>
	          <div class="field">
	    <%= f.label :introduction %>
	     <%= f.text_area :introduction, class: "introduction" %>
	          </div>
          <br><%= f.submit "Update User" %>

        <% end %>
    </div>
   </div>
</div>

app/views/users/edit.html.erb
<div class="error">
<% if @user.errors.any? %>
      <h3> <%= @user.errors.count %> error prohibited this obj from being saved:</h3>
       <% @user.errors.full_messages.each do |message| %>
           <%= message %>
       <% end %>
   <% end %>
  </div>

<div class= "body">
  <div class= "container">
    <h2> User info</h2>
    <div class="low">
	    <%= form_for(@user) do |f| %>
	    <div class="field">
		    <%= f.label :name %>
		      <%= f.text_field :name, autofocus: true, class: "name" %>
	    </div>
	      <div class="field">
	    <%= f.label :image %>
	          <%= f.attachment_field :profile_image, class: "user_image" %>
	      </div>
	          <div class="field">
	    <%= f.label :introduction %>
	     <%= f.text_area :introduction, class: "introduction" %>
	          </div>
          <br><%= f.submit "Update User" %>

        <% end %>
    </div>
   </div>
</div>

app/views/users/index.erb
<div class="container">
    <div class="row">
  <%= render 'books/list', book_images: @book_images, user: current_user, book: @book %>


  	<div class="col-xs-9">
      			<h2> Users</h2>
	      		  <table class="table table-hover table-inverse">
			        <thead>
				    	<tr>
				    		<th> image</th>
				    		<th> name</th>
				    	</tr>
				    </thead>
				    <% @users.each do |user| %>
				    <tbody>
				    	 <tr>
				    	 	<td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", :size =>"50x50" %></td>
				    	    <td><%= user.name %></td>
				    	    <td><%= link_to "show", user_path(user), class: "user_#{user.id}" %></td>
				    	 </tr>
				    </tbody>
				    <% end %>
			      </table>
			    </div>
		    </div>
		</div>
	</div>

</body>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
  <%= render 'books/list', book_images: @book_images, user: current_user, book: @book %>


  	<div class="col-xs-9">
      			<h2> Users</h2>
	      		  <table class="table table-hover table-inverse">
			        <thead>
				    	<tr>
				    		<th> image</th>
				    		<th> name</th>
				    	</tr>
				    </thead>
				    <% @users.each do |user| %>
				    <tbody>
				    	 <tr>
				    	 	<td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", :size =>"50x50" %></td>
				    	    <td><%= user.name %></td>
				    	    <td><%= link_to "show", user_path(user), class: "user_#{user.id}" %></td>
				    	 </tr>
				    </tbody>
				    <% end %>
			      </table>
			    </div>
		    </div>
		</div>
	</div>

</body>

app/views/users/show.html.erb
<body>
	<div class="body">
		<!-- / -->
		<%= render 'books/list', book_images: @book_images, user: @user, book: @book %>

                <!-- / -->
				<div class="col-xs-9">
				<h2> Books</h2>
				<table class="table">

					<thead>
				    	<tr>
				    		<th></th>
				    		<th> Title</th>
				    		<th> Opinion</th>
				    		<th colspan="3"></th>
				    	</tr>
				    </thead>
					<% @books.each do |book| %>
					<tbody>
						<tr>
							<td><%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", :size =>"50x50" %></td>
							<td><%= link_to book.title, "/books/#{book.id}" %></td>
							<td><%= book.body %></td>
						</tr>
					<% end %>
				   </tbody>
				</table>
			</div>
	</div>
</body>